# Generated by Django 4.2.7 on 2026-03-31 06:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlagiarismCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="查重检测的文本标题，最长500个字符",
                        max_length=500,
                        verbose_name="检测标题",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="需要进行查重检测的文本内容，支持长文本",
                        verbose_name="检测内容",
                    ),
                ),
                (
                    "similarity_percentage",
                    models.FloatField(
                        blank=True,
                        default=None,
                        help_text="文本相似度百分比，取值范围[0, 100]",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="相似度百分比",
                    ),
                ),
                (
                    "report_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="查重检测详细报告的访问链接，为空表示无报告链接",
                        max_length=500,
                        verbose_name="详细报告链接",
                    ),
                ),
                (
                    "report_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="查重检测的结构化报告数据（JSON格式），默认空字典",
                        verbose_name="检测报告数据",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "检测中"),
                            ("completed", "已完成"),
                            ("failed", "检测失败"),
                        ],
                        default="processing",
                        help_text="检测流程状态：processing-检测中，completed-已完成，failed-检测失败",
                        max_length=20,
                        verbose_name="检测状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="检测请求创建时间，自动记录，不可手动修改",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="检测记录更新时间，每次保存自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="检测完成时间，仅状态为「已完成」时自动填充",
                        null=True,
                        verbose_name="完成时间",
                    ),
                ),
            ],
            options={
                "verbose_name": "查重检测记录",
                "verbose_name_plural": "查重检测记录",
                "db_table": "plagiarism_checks",
                "ordering": ["-created_at"],
            },
        ),
    ]
