# Generated by Django 4.2.7 on 2026-03-31 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_pc", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="plagiarismcheck",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="发起查重检测的用户，用户删除时仅置空关联，不删除检测记录",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plagiarism_checks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="关联用户",
            ),
        ),
        migrations.AddIndex(
            model_name="plagiarismcheck",
            index=models.Index(
                fields=["user", "status"], name="plagiarism__user_id_7207f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plagiarismcheck",
            index=models.Index(
                fields=["status", "created_at"], name="plagiarism__status_57d34b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plagiarismcheck",
            index=models.Index(
                fields=["completed_at"], name="plagiarism__complet_953815_idx"
            ),
        ),
    ]
