# Generated by Django 4.2.7 on 2026-03-31 06:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneratedPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="论文标题，最长100个字符",
                        max_length=100,
                        validators=[django.core.validators.MaxLengthValidator(100)],
                        verbose_name="论文标题",
                    ),
                ),
                (
                    "requirements",
                    models.TextField(
                        help_text="用户提出的论文生成需求（如主题、字数、结构要求等）",
                        verbose_name="生成要求",
                    ),
                ),
                (
                    "template",
                    models.TextField(
                        blank=True,
                        help_text="论文生成所用的模板文本，为空时使用系统默认模板",
                        verbose_name="模板内容",
                    ),
                ),
                (
                    "abstract",
                    models.TextField(
                        blank=True,
                        help_text="生成的论文中文摘要",
                        verbose_name="中文摘要",
                    ),
                ),
                (
                    "key_words",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="中文关键词列表，如 ['AI', '深度学习']",
                        verbose_name="中文关键词",
                    ),
                ),
                (
                    "abstract_en",
                    models.TextField(
                        blank=True,
                        help_text="生成的论文英文摘要",
                        verbose_name="英文摘要",
                    ),
                ),
                (
                    "key_words_en",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="英文关键词列表",
                        verbose_name="英文关键词",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="生成的论文完整正文内容",
                        verbose_name="论文正文",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="论文核心结论与总结",
                        verbose_name="论文总结",
                    ),
                ),
                (
                    "thank_words",
                    models.TextField(
                        blank=True, help_text="论文致谢部分内容", verbose_name="致谢语"
                    ),
                ),
                (
                    "literature",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="参考文献列表（结构化数据）",
                        verbose_name="参考文献",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "生成中"),
                            ("completed", "已完成"),
                            ("failed", "生成失败"),
                        ],
                        default="generating",
                        help_text="论文生成状态：generating-生成中，completed-已完成，failed-生成失败",
                        max_length=20,
                        verbose_name="生成状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="生成请求创建时间，自动记录，不可手动修改",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，每次保存自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="论文生成完成时间，仅状态为「已完成」时自动填充",
                        null=True,
                        verbose_name="完成时间",
                    ),
                ),
            ],
            options={
                "verbose_name": "论文生成记录",
                "verbose_name_plural": "论文生成记录",
                "db_table": "generated_papers",
                "ordering": ["-created_at"],
            },
        ),
    ]
