# Generated by Django 4.2.7 on 2026-03-31 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_gp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedpaper",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="发起论文生成的用户，用户删除时仅置空关联，不删除生成记录",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_papers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="关联用户",
            ),
        ),
        migrations.AddIndex(
            model_name="generatedpaper",
            index=models.Index(
                fields=["user", "status"], name="generated_p_user_id_7dd5e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedpaper",
            index=models.Index(
                fields=["status", "created_at"], name="generated_p_status_8775f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedpaper",
            index=models.Index(
                fields=["completed_at"], name="generated_p_complet_4c3559_idx"
            ),
        ),
    ]
