# Generated by Django 4.2.7 on 2026-06-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_gp", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedpaper",
            name="failed_reason",
            field=models.TextField(
                blank=True,
                help_text="任务失败时的错误信息",
                null=True,
                verbose_name="失败原因",
            ),
        ),
        migrations.AddField(
            model_name="generatedpaper",
            name="task_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Celery任务ID",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="任务ID",
            ),
        ),
        migrations.AlterField(
            model_name="generatedpaper",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "排队中"),
                    ("generating", "生成中"),
                    ("completed", "已完成"),
                    ("failed", "生成失败"),
                ],
                default="queued",
                help_text="论文生成状态：queued-排队中，generating-生成中，completed-已完成，failed-生成失败",
                max_length=20,
                verbose_name="生成状态",
            ),
        ),
    ]
