# Generated by Django 4.2.7 on 2026-03-31 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_security", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="verifycode",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "验证码记录",
                "verbose_name_plural": "验证码记录",
            },
        ),
        migrations.AlterModelTable(
            name="verifycode",
            table="security_verify_code",
        ),
    ]
