# Generated by Django 4.2.7 on 2025-12-22 01:48

import app.users.models.users
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="用户自定义昵称，唯一标识，最长30个字符",
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="用户名",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="用于登录和接收验证码，格式为11位数字",
                        max_length=11,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^1[3-9]\\d{9}$", message="请输入有效的11位手机号码"
                            )
                        ],
                        verbose_name="手机号码",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="用于接收邮件通知，需符合邮箱格式",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="邮箱",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default="/static/avatars/default.png",
                        help_text="用户头像图片，支持JPG/PNG格式，建议尺寸200x200",
                        null=True,
                        upload_to=app.users.models.users.user_avatar_upload_path,
                        verbose_name="头像",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="个人简介，最长500个字符",
                        max_length=500,
                        null=True,
                        verbose_name="个人简介",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="标记用户是否删除（软删除，不物理删除数据）",
                        verbose_name="是否软删除",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="用户可以登录到管理站点",
                        verbose_name="是否后台管理员",
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="用户拥有所有权限",
                        verbose_name="是否超级用户",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="是否允许用户登录（禁用账号时设为False）",
                        verbose_name="是否激活",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UsedLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("generate", "生成"), ("check", "检查")],
                        help_text="用户执行的操作类型：generate-生成，check-检查",
                        max_length=20,
                        verbose_name="用户行为",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        help_text="模型名称",
                        max_length=20,
                        null=True,
                        verbose_name="模型名称",
                    ),
                ),
                (
                    "token_quota",
                    models.CharField(
                        blank=True,
                        help_text="消耗的token额度",
                        max_length=100,
                        null=True,
                        verbose_name="使用额度",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="日志创建时间，自动记录，不可修改",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="日志更新时间，自动记录，每次保存都会更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="与用户一对一关联，用户删除时日志不删除，仅置空用户关联",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="used_log",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "使用日志",
                "verbose_name_plural": "使用日志",
                "db_table": "used_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlagiarismCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="查重检测的文本标题，最长500个字符",
                        max_length=500,
                        verbose_name="检测标题",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="需要进行查重检测的文本内容，支持长文本",
                        verbose_name="检测内容",
                    ),
                ),
                (
                    "similarity_percentage",
                    models.FloatField(
                        blank=True,
                        default=None,
                        help_text="文本相似度百分比，取值范围[0, 100]",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="相似度百分比",
                    ),
                ),
                (
                    "report_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="查重检测详细报告的访问链接，为空表示无报告链接",
                        max_length=500,
                        verbose_name="详细报告链接",
                    ),
                ),
                (
                    "report_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="查重检测的结构化报告数据（JSON格式），默认空字典",
                        verbose_name="检测报告数据",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "检测中"),
                            ("completed", "已完成"),
                            ("failed", "检测失败"),
                        ],
                        default="processing",
                        help_text="检测流程状态：processing-检测中，completed-已完成，failed-检测失败",
                        max_length=20,
                        verbose_name="检测状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="检测请求创建时间，自动记录，不可手动修改",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="检测记录更新时间，每次保存自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="检测完成时间，仅状态为「已完成」时自动填充",
                        null=True,
                        verbose_name="完成时间",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="发起查重检测的用户，用户删除时仅置空关联，不删除检测记录",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plagiarism_checks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "查重检测记录",
                "verbose_name_plural": "查重检测记录",
                "db_table": "plagiarism_checks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="论文标题，最长100个字符",
                        max_length=100,
                        validators=[django.core.validators.MaxLengthValidator(100)],
                        verbose_name="论文标题",
                    ),
                ),
                (
                    "requirements",
                    models.TextField(
                        help_text="用户提出的论文生成需求（如主题、字数、结构要求等）",
                        verbose_name="生成要求",
                    ),
                ),
                (
                    "template",
                    models.TextField(
                        blank=True,
                        help_text="论文生成所用的模板文本，为空时使用系统默认模板",
                        verbose_name="模板内容",
                    ),
                ),
                (
                    "abstract",
                    models.TextField(
                        blank=True,
                        help_text="生成的论文中文摘要",
                        verbose_name="中文摘要",
                    ),
                ),
                (
                    "key_words",
                    models.TextField(
                        blank=True,
                        help_text="生成的论文中文关键词（建议用分号分隔）",
                        verbose_name="中文关键词",
                    ),
                ),
                (
                    "abstract_en",
                    models.TextField(
                        blank=True,
                        help_text="生成的论文英文摘要",
                        verbose_name="英文摘要",
                    ),
                ),
                (
                    "key_words_en",
                    models.TextField(
                        blank=True,
                        help_text="生成的论文英文关键词（建议用分号分隔）",
                        verbose_name="英文关键词",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="生成的论文完整正文内容",
                        verbose_name="论文正文",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="论文核心结论与总结",
                        verbose_name="论文总结",
                    ),
                ),
                (
                    "thank_words",
                    models.TextField(
                        blank=True, help_text="论文致谢部分内容", verbose_name="致谢语"
                    ),
                ),
                (
                    "literature",
                    models.TextField(
                        blank=True,
                        help_text="生成的论文参考文献列表",
                        verbose_name="参考文献",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "生成中"),
                            ("completed", "已完成"),
                            ("failed", "生成失败"),
                        ],
                        default="generating",
                        help_text="论文生成状态：generating-生成中，completed-已完成，failed-生成失败",
                        max_length=20,
                        verbose_name="生成状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="生成请求创建时间，自动记录，不可手动修改",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="记录更新时间，每次保存自动更新",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="论文生成完成时间，仅状态为「已完成」时自动填充",
                        null=True,
                        verbose_name="完成时间",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="发起论文生成的用户，用户删除时仅置空关联，不删除生成记录",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_papers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "论文生成记录",
                "verbose_name_plural": "论文生成记录",
                "db_table": "generated_papers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["phone"], name="users_phone_af6883_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="users_usernam_baeb4b_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_deleted", "is_active"], name="users_is_dele_399fe2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["created_at"], name="users_created_6541e9_idx"),
        ),
        migrations.AddIndex(
            model_name="usedlog",
            index=models.Index(
                fields=["user", "created_at"], name="used_logs_user_id_924d14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usedlog",
            index=models.Index(
                fields=["action", "model_name"], name="used_logs_action_9d4476_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plagiarismcheck",
            index=models.Index(
                fields=["user", "status"], name="plagiarism__user_id_7207f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plagiarismcheck",
            index=models.Index(
                fields=["status", "created_at"], name="plagiarism__status_57d34b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plagiarismcheck",
            index=models.Index(
                fields=["completed_at"], name="plagiarism__complet_953815_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedpaper",
            index=models.Index(
                fields=["user", "status"], name="generated_p_user_id_7dd5e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedpaper",
            index=models.Index(
                fields=["status", "created_at"], name="generated_p_status_8775f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedpaper",
            index=models.Index(
                fields=["completed_at"], name="generated_p_complet_4c3559_idx"
            ),
        ),
    ]
