# Generated by Django 4.2.7 on 2026-04-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_phone_change_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
