# Generated by Django 4.2.7 on 2026-06-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0002_alter_user_last_phone_change_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token_version",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
