# Generated by Django 4.2.7 on 2025-12-22 07:59

import app.users.models.users
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0002_user_groups_user_user_permissions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usedlog",
            name="ip_addr",
            field=models.CharField(
                blank=True,
                help_text="请求的IP地址",
                max_length=50,
                null=True,
                verbose_name="IP地址",
            ),
        ),
        migrations.AddField(
            model_name="usedlog",
            name="user_agent",
            field=models.CharField(
                blank=True,
                help_text="请求的用户代理信息",
                max_length=255,
                null=True,
                verbose_name="用户代理",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="static/avatars/default.png",
                help_text="用户头像图片，支持JPG/PNG格式，建议尺寸200x200",
                null=True,
                upload_to=app.users.models.users.user_avatar_upload_path,
                verbose_name="头像",
            ),
        ),
    ]
