# Generated by Django 4.2.7 on 2025-12-26 07:50

import app.users.models.users
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0003_usedlog_ip_addr_usedlog_user_agent_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_phone_af6883_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_usernam_baeb4b_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_is_dele_399fe2_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_created_6541e9_idx",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_deleted",
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="static/avatars/default.png",
                null=True,
                upload_to=app.users.models.users.user_avatar_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[django.core.validators.RegexValidator("^1[3-9]\\d{9}$")],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
