# Generated by Django 4.2.7 on 2026-01-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0004_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
