# Generated by Django 4.2.7 on 2026-01-08 01:55

import app.users.models.users_manage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0005_user_display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=app.users.models.users_manage.user_avatar_upload_path,
            ),
        ),
    ]
