# Generated by Django 4.2.7 on 2026-01-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0006_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_phone_change_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, editable=False, max_length=30, null=True, unique=True
            ),
        ),
    ]
